import { createAfricaniesClient } from '../../dist/browser.js';
import { preparePurchaseRequest } from '../../dist/ui.js';
import { tomorrowLocal } from './date.js';
const stage=document.querySelector('#stage'),status=document.querySelector('#status'),keyInput=document.querySelector('#key'),realSandbox=document.querySelector('#real-sandbox');let client,completedRequest,selectedRate;
const fixtureRate={name:'Fixture Air',slug:'fixture-air',mode:'SFN',total_amount:5000,discount_amount:0,payment_amount:5000,total_item_value:2500,charges:{shipment_cost:5000,insurance_cost:0,pickup_cost:0,last_mile_delivery_cost:0,vat:0},others:{min_day:'2',max_day:'4',currency:'NGN'}};const envelope=(data)=>({success:true,status_code:200,message:'Local fixture',data});
const fixtureAddress=(type)=>({first_name:type==='sender'?'Ada':'Grace',last_name:'Lovelace',email:`${type}@example.com`,phone:'1234567890',country:type==='sender'?'NG':'US',state:type==='sender'?'LA':'MA',city:type==='sender'?'Lagos':'Boston',address:'1 Example Street',address_in_detail:'1 Example Street',address_landmark:'Example',zip_code:type==='sender'?'100001':'02125',type,longitude:null,latitude:null,google_address:'0'});const fixtureDraft={addresses:{sender:fixtureAddress('sender'),receiver:fixtureAddress('receiver')},boxes:[{index:0,length:30,width:20,height:15,weight:1.2,items:[{name:'Handbags',description:'Leather handbag',product_hs_code:'4202210000',product_hs_code_description:'Handbags',weight:1.2,unit_price:1250,country:'NG',quantity:1,amount:1250}]}],units:{dimension:'cm',mass:'KG'},last_mile_delivery:true,pickup:false,is_insured:'0'};
const fixtureTransport={async request(request){if(request.path==='/shipment/carriers')return envelope([]);if(request.path==='/shipment/rates')return envelope([fixtureRate]);if(request.path.startsWith('/product/search/'))return envelope([{id:1,hs_code:'4202210000',name:'Handbags',active:true,deleted_at:null,created_at:'2026-01-01',updated_at:null}]);if(request.path==='/shipment/purchase')return envelope({reference:'FIXTURE-SHIPMENT',tracking_number:'FIXTURE-TRACKING',tracking_url:'https://example.com/tracking',documents:{waybill_doc:null,insurance_doc:null,invoice_doc:'JVBERi0xLjQ='},waybill_is_url:0,insurance_is_url:0,invoice_is_url:0,mode:'SFN'});throw new Error(`No local fixture for ${request.path}`)}};
realSandbox.addEventListener('change',()=>{keyInput.disabled=!realSandbox.checked;keyInput.required=realSandbox.checked;if(!realSandbox.checked)keyInput.value=''});document.querySelector('#logout').addEventListener('click',reset);
document.querySelector('#login').addEventListener('submit',async(event)=>{event.preventDefault();client=undefined;stage.replaceChildren();try{const candidate=realSandbox.checked?createAfricaniesClient({environment:'test',shipmentMode:'SFN',auth:{encodedKey:keyInput.value.trim()}}):createAfricaniesClient({environment:'test',shipmentMode:'SFN',transport:fixtureTransport});await candidate.carriers.list();client=candidate;document.querySelector('#login').hidden=true;document.querySelector('#logout').hidden=false;status.textContent=realSandbox.checked?'Sandbox connected.':'Local no-network fixtures connected.';showBuilder()}catch(error){client=undefined;status.textContent=error instanceof Error?error.message:'Connection failed.'}finally{keyInput.value=''}});
function reset(){client=undefined;completedRequest=undefined;selectedRate=undefined;keyInput.value='';realSandbox.checked=false;keyInput.disabled=true;keyInput.required=false;stage.replaceChildren();document.querySelector('#login').hidden=false;document.querySelector('#logout').hidden=true;status.textContent='Session cleared.'}
function showBuilder(){const element=document.createElement('africanies-shipment-builder');element.client=client;if(!realSandbox.checked)element.value=structuredClone(fixtureDraft);element.addEventListener('africanies-complete',({detail})=>{completedRequest=detail;showRates()},{once:true});stage.replaceChildren(element)}
function showRates(){const element=document.createElement('africanies-rate-selection');element.client=client;element.request=completedRequest;element.addEventListener('africanies-complete',({detail})=>{selectedRate=detail.rate;showPayment()},{once:true});stage.replaceChildren(element)}
function showPayment(){stage.replaceChildren(document.querySelector('#payment').content.cloneNode(true));document.querySelector('#confirm-payment').addEventListener('click',()=>{const outcome=document.querySelector('#outcome').value;if(outcome!=='success'){document.querySelector('#payment-status').textContent=`PayDemo ${outcome}. No purchase element was mounted.`;return}showPurchase()})}
function showPurchase(){const prepared=preparePurchaseRequest(completedRequest,{assignedDate:tomorrowLocal(),externalReference:crypto.randomUUID(),rate:selectedRate,fileIsUrl:1});if(!prepared.success){status.textContent=prepared.issues.map(({path,message})=>`${path}: ${message}`).join('; ');return}const element=document.createElement('africanies-purchase-confirmation');element.client=client;element.request=prepared.request;element.addEventListener('africanies-complete',({detail})=>{status.textContent=`Shipment ${detail.data.reference} purchased.`});stage.replaceChildren(element)}
