export { resolveAuthorization, type AfricaniesAuth, type EncodedCredentials, type RawCredentials } from './auth.js';
export { AFRICANIES_ENVIRONMENTS, createAfricaniesClient } from './client.js';
export type { AfricaniesClient, AfricaniesClientConfig, UploadedFile, UploadOptions } from './client.js';
export { AfricaniesError, categoryForStatus, redactUrl } from './errors.js';
export type { AfricaniesErrorCategory, AfricaniesErrorOptions } from './errors.js';
export { createFetchTransport } from './transport.js';
export type { AfricaniesTransport, FetchTransportOptions, HttpMethod, TransportRequest } from './transport.js';
export type * from './types.js';
export { assertShipmentGeography, assertShipmentRequest, inferShipmentMode, isNigeriaCountry, shipmentGeographyIssues, shipmentRequestIssues } from './shipment-validation.js';
export { calculatePackaging } from './packaging.js';
export type * from './packaging.js';
export { buildRateRequestFromPackaging, createCheckoutPurchaseIntent, createCheckoutShippingQuote, purchaseAfterPayment, selectCheckoutRate } from './checkout.js';
export type * from './checkout.js';
