import * as Shipping from '@africanies/shipping/browser';
import './styles.css';
import { WAREHOUSE_ADDRESS, minimumAssignedDate, payDemoResult } from './demo-state.js';

const $ = (selector) => document.querySelector(selector);
const money = (value, currency = 'NGN') => new Intl.NumberFormat('en-NG', { style: 'currency', currency }).format(Number(value));
const escape = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
let client; let rateRequest; let packaging; let quote; let selected; let externalReference; let purchaseState = 'idle'; let documentUrls = [];

function setError(message = '') { $('#manual-error').textContent = message; $('#manual-error').hidden = !message; if (message) $('#manual-error').focus(); }
function setStatus(message) { $('#manual-status').textContent = message; }
function progress(active) { document.querySelectorAll('[data-manual-progress]').forEach((node) => { const index = Number(node.dataset.manualProgress); node.classList.toggle('active', index === active); node.classList.toggle('done', index < active); if (index === active) node.setAttribute('aria-current', 'step'); else node.removeAttribute('aria-current'); }); }
function receiver() { return { first_name:'Jane',last_name:'Smith',email:'receiver@example.com',phone:'0987654321',alternate_phone:null,country:'US',state:'MA',city:'Boston',address:'17 Maryland St Boston MA USA',address_in_detail:'17 Maryland St Boston MA USA',address_landmark:'17 Maryland St Boston MA USA',zip_code:'02125',type:'receiver',longitude:-71.0598,latitude:42.3601,street_number:null,street_name:null,google_address:'0' }; }
function draft() { return { addresses:{sender:{...WAREHOUSE_ADDRESS,first_name:'John',last_name:'Doe',email:'sender@example.com',phone:'1234567890',city:'Isolo',address:'17 Idowu Oshinfodunrin St, Isaga Tedo, Lagos 102214, Lagos, Nigeria',address_in_detail:'17 Idowu Oshinfodunrin St, Isaga Tedo, Lagos 102214, Lagos, Nigeria',address_landmark:'17 Idowu Oshinfodunrin St, Isaga Tedo, Lagos 102214, Lagos, Nigeria',zip_code:'102214'},receiver:receiver()},boxes:[{index:'1',length:'10',width:'10',height:'10',weight:'5',items:[{name:'Electronics Accessories',description:'This is an item',product_hs_code:'',weight:'1.5',price:1500,unit_price:1500,country:'NG',quantity:'1',amount:'1500'},{name:'Smartphone Case',description:'This is another item',product_hs_code:'',weight:'0.3',price:1500,unit_price:1500,country:'NG',quantity:'1',amount:'1500'}]}],units:{dimension:'cm',mass:'KG'},last_mile_delivery:true,pickup:false,is_insured:'0' }; }

function reset() { client=undefined; rateRequest=undefined; packaging=undefined; quote=undefined; selected=undefined; externalReference=undefined; purchaseState='idle'; documentUrls.forEach(URL.revokeObjectURL); documentUrls=[]; $('#manual-key').value=''; $('#manual-app').hidden=true; $('#manual-login').hidden=false; $('#manual-logout').hidden=true; $('#manual-login-status').textContent=''; $('#manual-workspace').replaceChildren(); setError(); $('#manual-key').focus(); }

$('#manual-login-form').addEventListener('submit', async (event) => { event.preventDefault(); const key=$('#manual-key').value.trim(); $('#manual-login-status').textContent='Checking sandbox credential…'; client=undefined; try { const candidate=Shipping.createAfricaniesClient({environment:'test',shipmentMode:'SFN',auth:{encodedKey:key}}); const response=await candidate.carriers.list(); if(!response?.success)throw new Error(response?.message||'Credential validation failed.'); client=candidate; $('#manual-login').hidden=true; $('#manual-app').hidden=false; $('#manual-logout').hidden=false; showBuilder(); } catch (cause) { $('#manual-login-status').textContent=cause instanceof Error?cause.message:'Credential validation failed.'; } finally { $('#manual-key').value=''; } });
$('#manual-logout').addEventListener('click', reset);

function showBuilder() { progress(0); setStatus('Enter every box and item measurement. Product classification is searched through the Products API.'); const builder=document.createElement('africanies-shipment-builder'); builder.client=client; builder.value=draft(); builder.addEventListener('africanies-complete',(event)=>{ rateRequest=event.detail; packaging=Shipping.calculatePackaging([], {mode:'manual',boxes:rateRequest.boxes}); if(!packaging.valid){setError(packaging.issues.map((issue)=>`${issue.path}: ${issue.message}`).join(' '));return;} showRates(); },{once:true}); $('#manual-workspace').replaceChildren(builder); }
function showRates() { progress(1); setError(); setStatus('Loading rates for the host-supplied boxes.'); const rates=document.createElement('africanies-rate-selection'); rates.client=client; rates.request=rateRequest; rates.addEventListener('africanies-complete',(event)=>{ const rate=event.detail.rate; quote=Shipping.createCheckoutShippingQuote(rateRequest,packaging,event.detail.rates??[rate]); selected=Shipping.selectCheckoutRate(quote,rate.slug); showPayment(rate); },{once:true}); $('#manual-workspace').replaceChildren(rates); }
function showPayment(rate) { progress(2); externalReference??=`MANUAL-${crypto.randomUUID?.()??Date.now()}`; const merchandise=rateRequest.boxes.flatMap((box)=>box.items).reduce((sum,item)=>sum+item.amount,0); const total=merchandise+selected.shippingCost; const panel=document.createElement('section'); panel.className='panel manual-payment'; panel.innerHTML=`<p class="eyebrow">PayDemo simulation</p><h2>Confirm host payment</h2><p>This fake gateway confirms merchandise plus delivery. The SDK shipping intent binds only ${escape(money(selected.shippingCost,selected.currency))}.</p><dl class="payment-context"><div><dt>Reference</dt><dd>${escape(externalReference)}</dd></div><div><dt>Carrier</dt><dd>${escape(rate.name)}</dd></div><div><dt>Merchandise</dt><dd>${escape(money(merchandise,selected.currency))}</dd></div><div><dt>Full total</dt><dd>${escape(money(total,selected.currency))}</dd></div></dl><label>Simulation outcome<select id="manual-payment-outcome"><option value="success">Approve full payment</option><option value="failed">Decline payment</option><option value="cancelled">Cancel payment</option></select></label><button id="manual-pay" class="primary wide">Simulate payment and purchase</button>`; $('#manual-workspace').replaceChildren(panel); $('#manual-pay').addEventListener('click',()=>void purchase(rate,merchandise,total)); }
async function purchase(rate,merchandise,total) { setError(); if(purchaseState==='uncertain'){setError(`The prior result is uncertain. Reconcile ${externalReference} before retrying.`);return;} const payment=payDemoResult($('#manual-payment-outcome').value,{amount:total,currency:selected.currency}); if(!payment.confirmed){setError(`PayDemo payment was ${payment.status}. No shipment was purchased.`);return;} const prepared=Shipping.preparePurchaseRequest(rateRequest,{assignedDate:minimumAssignedDate(),externalReference,rate,shipmentMethodSlug:rate.slug,fileIsUrl:1}); if(!prepared.success){setError(prepared.issues.map((issue)=>`${issue.path}: ${issue.message}`).join(' '));return;} const intent=Shipping.createCheckoutPurchaseIntent(prepared.request,selected); purchaseState='submitting'; try { const response=await Shipping.purchaseAfterPayment(client,intent,{confirmed:true,reference:payment.id,confirmedAt:new Date().toISOString(),intentId:intent.id,amount:intent.amount,currency:intent.currency}); purchaseState='purchased'; showResult(response.data,payment,merchandise); } catch(cause){purchaseState=isDefinitivePurchaseFailure(cause)?'failed':'uncertain'; const reconciliation=purchaseState==='uncertain'?` Reconcile ${externalReference} before retrying.`:''; setError(`${cause instanceof Error?cause.message:'Purchase failed.'}${reconciliation}`);} }
function isDefinitivePurchaseFailure(cause) { return cause instanceof Shipping.AfricaniesError && (cause.category==='validation'||[400,401,403,404,422,424].includes(cause.status)); }
function showResult(result,payment,merchandise) { progress(3); setStatus('Manual package shipment purchased.'); const safeUrl=(value)=>{try{const url=new URL(value);return url.protocol==='https:'?url.href:null;}catch{return null;}}; const tracking=safeUrl(result.tracking_url); const docs=[['Waybill',result.documents.waybill_doc,result.waybill_is_url],['Invoice',result.documents.invoice_doc,result.invoice_is_url],['Insurance',result.documents.insurance_doc,result.insurance_is_url]]; const delivery=payment.amount-merchandise; $('#manual-workspace').innerHTML=`<section class="panel manual-result"><p class="eyebrow">Manual shipment complete</p><h2>${escape(result.reference)}</h2><p>Tracking: <strong>${escape(result.tracking_number)}</strong></p>${tracking?`<a class="button-link primary" href="${escape(tracking)}" target="_blank" rel="noopener noreferrer">Track shipment</a>`:''}<div class="panel payment-record" role="status"><div class="payment-record-head"><div><small>PAYDEMO FULL ORDER + DELIVERY</small><h3>Payment recorded</h3></div><span class="payment-status-badge">Paid</span></div><strong class="payment-record-total">${escape(money(payment.amount,payment.currency))}</strong><dl><div><dt>Reference</dt><dd>${escape(payment.id)}</dd></div><div><dt>Merchandise</dt><dd>${escape(money(merchandise,payment.currency))}</dd></div><div><dt>Delivery</dt><dd>${escape(money(delivery,payment.currency))}</dd></div><div><dt>Confirmed</dt><dd>${escape(payment.confirmedAt??'Confirmed by PayDemo')}</dd></div></dl></div><div class="documents">${docs.map(([label,value,flag])=>{const href=flag===1?safeUrl(value):null;return href?`<a class="document-card" href="${escape(href)}" target="_blank" rel="noopener noreferrer"><strong>${label}</strong><small>Open document</small></a>`:`<div class="document-card unavailable"><strong>${label}</strong><small>Not returned as HTTPS URL</small></div>`;}).join('')}</div></section>`; }
